In [15]:
import pandas as pd

In [16]:
# 1. Create a DataFrame for the 201908-citibike-tripdata data. 
file_to_load = "201908-citibike-tripdata.csv"
bikedata = pd.read_csv(file_to_load)

bike_data = pd.DataFrame(bikedata)

In [22]:
# 2. Check the datatypes of your columns. 
bike_data.dtypes

tripduration               datetime64[ns]
starttime                          object
stoptime                           object
start station id                  float64
start station name                 object
start station latitude            float64
start station longitude           float64
end station id                    float64
end station name                   object
end station latitude              float64
end station longitude             float64
bikeid                              int64
usertype                           object
birth year                          int64
gender                              int64
dtype: object

In [19]:
# 3. Convert the 'tripduration' column to datetime datatype.
bike_data['tripduration'] = bike_data['tripduration'].astype('datetime64[s]')

In [25]:
# 4. Check the datatypes of your columns. 
bike_data.sample(10)

,tripduration,starttime,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,end station longitude,bikeid,usertype,birth year,gender
221428,1970-01-01 00:02:28,2019-08-03 16:51:30.8640,2019-08-03 16:53:59.0690,3151.0,E 81 St & York Ave,40.772838,-73.949892,3140.0,1 Ave & E 78 St,40.771404,-73.953517,38433,Subscriber,1989,1
2209774,1970-01-01 00:05:38,2019-08-30 07:46:02.0760,2019-08-30 07:51:40.1670,366.0,Clinton Ave & Myrtle Ave,40.693261,-73.968896,323.0,Lawrence St & Willoughby St,40.692362,-73.986317,30769,Subscriber,1990,1
957035,1970-01-01 00:07:58,2019-08-13 12:45:13.8570,2019-08-13 12:53:12.5950,3112.0,Milton St & Franklin St,40.729060,-73.957790,460.0,S 4 St & Wythe Ave,40.712859,-73.965903,15756,Subscriber,1986,1
890067,1970-01-01 00:10:19,2019-08-12 16:31:28.6560,2019-08-12 16:41:47.7720,500.0,Broadway & W 51 St,40.762288,-73.983362,514.0,12 Ave & W 40 St,40.760875,-74.002777,30937,Customer,1972,1
1558607,1970-01-01 00:13:19,2019-08-21 10:17:03.6170,2019-08-21 10:30:22.8340,358.0,Christopher St & Greenwich St,40.732916,-74.007114,525.0,W 34 St & 11 Ave,40.755942,-74.002116,20326,Subscriber,1994,2
860283,1970-01-01 00:06:13,2019-08-12 08:44:06.9980,2019-08-12 08:50:20.0850,489.0,10 Ave & W 28 St,40.750664,-74.001768,505.0,6 Ave & W 33 St,40.749013,-73.988484,26573,Customer,1969,0
1275358,1970-01-01 00:36:30,2019-08-17 12:47:43.2900,2019-08-17 13:24:13.8170,280.0,E 10 St & 5 Ave,40.733320,-73.995101,447.0,8 Ave & W 52 St,40.763707,-73.985162,20130,Customer,1969,0
767856,1970-01-01 00:08:34,2019-08-10 21:11:40.1150,2019-08-10 21:20:14.3460,3756.0,White St & Moore St,40.704508,-73.935100,3074.0,Montrose Ave & Bushwick Ave,40.707678,-73.940162,38700,Customer,1969,0
367343,1970-01-01 00:05:26,2019-08-05 17:44:27.3330,2019-08-05 17:49:53.7480,3707.0,Lexington Ave & E 26 St,40.741459,-73.983293,501.0,FDR Drive & E 35 St,40.744219,-73.971212,33938,Subscriber,1989,2
1954034,1970-01-01 00:03:08,2019-08-26 18:41:09.0310,2019-08-26 18:44:17.3920,168.0,W 18 St & 6 Ave,40.739713,-73.994564,466.0,W 25 St & 6 Ave,40.743954,-73.991449,27103,Subscriber,1972,1

In [26]:
# 5. Export the Dataframe as a new CSV file without the index.
bike_data.to_csv("bikedatadf.csv", index=False)